development: &defaults
  adapter: postgis
  schema_search_path: "public"
  postgis_extension: true
  database: osm_new
  host: localhost
  username: corti
  password: password

test:
  <<: *defaults
  database: spatio_test

production:
  <<: *defaults
  database: spatio_prod
